version: "3.9"                  ### 2021/5/3現在の最新バージョン
services:
  test1:                        ### service名。docker-compose runの際はこれを指定する
    build: ./                   ### Dockfileの場所を指定。この場合はdocker-compose.yamlファイルと同階層を指定
    image: test-image:latest    ### buildと一緒に使用した場合、イメージ名の指定ができる
    volumes:                    ### ホストとコンテナで共有するディレクトリを選ぶ。
      - ./test:/test
    command: tail -f /dev/null  ### コンテナが実行するコマンドを選択。永続させたい場合tail -f /dev/null
  test2:
    image: test-image:latest    ### buildと一緒に使用しない場合、立ち上げるdocker imageを指定
